spring:
  config:
    import: optional:classpath:application-secret.yml
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:mysql://motio-cluster.cluster-cvyq8aykq5lv.ap-northeast-2.rds.amazonaws.com:3306/motio_dev?useSSL=false&characterEncoding=UTF-8
    username: admin
    password: m151507!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl_auto: validate
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 859f5bca699836d7d1d02da37f242e74
            redirect-uri: https://api.motiolab.com/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - account_email
              - birthyear
              - birthday
              - gender
              - name
              - phone_number
          naver:
            client-id: tT2FOtsuwL6LZE89sanx
            redirect-uri: https://api.motiolab.com/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email
              - profile_image
              - mobile
          apple:
            client-id: com.positive.test.oauth2.test
            redirect-uri: https://8b73-14-32-47-209.ngrok-free.app/login/oauth2/code/apple
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Apple
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/token
            user-name-attribute: sub
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  graphql:
    graphiql:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
      springframework:
        security: DEBUG
        web: DEBUG
jwt:
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

kakao:
  admin-key: ccd1308e2b23991be20bc1822c28ed53

naver-cloud:
  domain: https://sens.apigw.ntruss.com
  sms:
    serviceId: ncp:sms:kr:274281858019:positive-hotel

apple:
  auth:
    url: https://appleid.apple.com
  team:
    id: 249JP946MX
  redirect:
    url: https://positivehotelyoga.com/applelogin/callback
  client:
    id: com.motiolab.nabusi-ios
  key:
    id: K73M5XWDJ7
    path: appleKey/AuthKey_K73M5XWDJ7.p8

firebase:
  file:
    path: firebase/positive-hotel-firebase-adminsdk-on1ab-d21210d085.json

# aws
cloud:
  aws:
    image:
      saved:
        url: https://image-positivehotel-bucket.s3.ap-northeast-2.amazonaws.com/standard
      dns:
        url: https://img.positivehotel.io
    s3:
      bucket: image-positivehotel-bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2

# tossed keys