spring:

  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    # Use Environment Variables for DB connection (Injected by GitHub Secrets)
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl_auto: validate
    properties:
      hibernate:
        show_sql: false
        highlight_sql: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 859f5bca699836d7d1d02da37f242e74
            redirect-uri: https://api.nabusi.com/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - account_email
              - birthyear
              - birthday
              - gender
              - name
              - phone_number
          naver:
            client-id: tT2FOtsuwL6LZE89sanx
            client-secret: ${NAVER_SECRET}
            redirect-uri: https://api.nabusi.com/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email
              - profile_image
              - mobile

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  graphql:
    graphiql:
      enabled: false
      
logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.springframework: INFO

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

kakao:
  admin-key: fc9a2392353a69910f77f44302c164ff

naver-cloud:
  accessKey: ${NAVER_CLOUD_ACCESS_KEY}
  secretKey: ${NAVER_CLOUD_SECRET_KEY}
  domain: https://sens.apigw.ntruss.com
  sms:
    serviceId: ncp:sms:kr:363881440036:nabusi

apple:
  auth:
    url: https://appleid.apple.com
  team:
    id: 249JP946MX
  redirect:
    url: https://positivehotelyoga.com/applelogin/callback
  client:
    id: com.motiolab.nabusi-ios
  key:
    id: K73M5XWDJ7
    path: appleKey/AuthKey_K73M5XWDJ7.p8

firebase:
  file:
    path: firebase/nabusi-f20e3-firebase-adminsdk-fbsvc-9902a35f55.json

# aws
cloud:
  aws:
    iamAccessKey: ${AWS_ACCESS_KEY}
    iamSecretKey: ${AWS_SECRET_KEY}
    image:
      saved:
        url: https://nabusi-image-bucket.s3.ap-northeast-2.amazonaws.com/standard
      dns:
        url: https://img.nabusi.com
    s3:
      bucket: nabusi-image-bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2

toss-pay:
  secretKey: ${TOSS_PAY_SECRET_KEY}